// <auto-generated />
namespace EBMTodo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class onlinemember_PMID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(onlinemember_PMID));
        
        string IMigrationMetadata.Id
        {
            get { return "201712190117432_onlinemember_PMID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
